skwissh/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import list_detail
from skwissh.generic_views import AddServerView, DeleteServerView, \
    UpdateServerView, DeleteGroupView, AddServerGroupView, UpdateServerGroupView, \
    DeleteProbeView, UpdateProbeView, AddProbeView
from skwissh.models import CronLog, ServerGroup, Server

staff_required = user_passes_test(lambda u: u.is_staff)


def get_nogroups():
    return Server.objects.filter(servergroup__isnull=True).order_by('hostname')


def get_groups():
    return ServerGroup.objects.all().order_by('name')

logs_info = {"queryset": CronLog.objects.all(),
             "template_name": 'cronlog_list.html',
             "paginate_by": 50,
             "extra_context": {
                               'groups': get_groups,
                               'nogroup_servers': get_nogroups,
                               }
}

urlpatterns = patterns('',

    # Skwissh index
    url(r'^$', 'skwissh.views.index', name='index'),

    # i18n
    url(r'^i18n/', include('django.conf.urls.i18n'), name="i18n"),

    # Login / logout.
    url(r'^login/$', 'skwissh.views.login_skwissh', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page": reverse_lazy('index')}),

    # Server
    url(r'^server-list/$', 'skwissh.views.server_list', name='server-list'),
    url(r'^server-detail/(\d+)/$', 'skwissh.views.server_detail', name='server-detail'),
    url(r'^add_server/$', staff_required(AddServerView.as_view()), name='add-server'),
    url(r'^delete_server/(?P<pk>[\w-]+)$', staff_required(DeleteServerView.as_view()), name='delete-server'),
    url(r'^update_server/(?P<pk>[\w-]+)$', staff_required(UpdateServerView.as_view()), name='update-server'),

    # Server Groups
    url(r'^add_group/$', staff_required(AddServerGroupView.as_view()), name='add-group'),
    url(r'^delete_group/(?P<pk>[\w-]+)$', staff_required(DeleteGroupView.as_view()), name='delete-group'),
    url(r'^update_group/$', staff_required(UpdateServerGroupView.as_view()), name='update-group'),

    # Probes
    url(r'^list_probe/$', 'skwissh.views.probe_list', name='probe-list'),
    url(r'^add_probe/$', staff_required(AddProbeView.as_view()), name='add-probe'),
    url(r'^update_probe/$', staff_required(UpdateProbeView.as_view()), name='update-probe'),
    url(r'^delete_probe/(?P<pk>[\w-]+)$', staff_required(DeleteProbeView.as_view()), name='delete-probe'),

    # Logs
    #url(r'^logs/$', CronLogListView.as_view(), name='logs-list'),
    url(r'^logs/$', login_required(list_detail.object_list), logs_info, name='logs-list'),

    # Ajax
    url(r'^mesures/(\d+)/(\d+)/(\w+)/$', 'skwissh.views.mesures', name='mesures'),

    # Ajax for Android
    url(r'^graphtypes/$', 'skwissh.views.graphtypes', name='graphtypes'),
    url(r'^server_groups/$', 'skwissh.views.server_groups', name='server-groups'),
    url(r'^servers/(\d+)/$', 'skwissh.views.servers', name='servers'),
    url(r'^sensors/(\d+)/$', 'skwissh.views.sensors', name='sensors'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        url(r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),
    )

skwissh/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from skwissh.fields import EncryptedCharField
import datetime


class GraphType(models.Model):
    name = models.CharField(max_length=255, verbose_name=_(u"Nom"), null=True, blank=True)
    options = models.TextField(verbose_name=_(u"Options jqPlot"), null=True, blank=True)
    date_created = models.DateTimeField(verbose_name=_(u"Date de création"), null=True, auto_now_add=True, default=datetime.datetime.now())
    date_modified = models.DateTimeField(verbose_name=_(u"Date de modification"), null=True, auto_now=True, default=datetime.datetime.now())

    def __unicode__(self):
        return u"%s" % self.name

    class Meta:
        verbose_name = _(u"type de graphique")
        verbose_name_plural = _(u"types de graphiques")
        ordering = ['name']


def get_default_graph_type():
    return GraphType.objects.get(name="linegraph")


class Probe(models.Model):
    display_name = models.CharField(max_length=255, verbose_name=_(u"Nom de la sonde"))
    addon_name = models.CharField(max_length=255, verbose_name=_(u"Infos complémentaires (version linux...)"), null=True, blank=True)
    ssh_command = models.TextField(verbose_name=_(u"Commande SSH"))
    use_sudo = models.BooleanField(verbose_name=_(u"Utilise 'sudo' ?"), default=False)
    python_parse = models.TextField(verbose_name=_(u"Commande Python de parsing"), null=True, blank=True, default="output = output")
    graph_type = models.ForeignKey(GraphType, verbose_name=_(u"Type de graphique par défaut"), default=get_default_graph_type)
    probe_unit = models.CharField(max_length=10, verbose_name=_(u"Unité"), null=True, blank=True)
    probe_labels = models.CharField(max_length=255, verbose_name=_(u"Labels des valeurs"), null=True, blank=True)
    date_created = models.DateTimeField(verbose_name=_(u"Date de création"), null=True, auto_now_add=True, default=datetime.datetime.now())
    date_modified = models.DateTimeField(verbose_name=_(u"Date de modification"), null=True, auto_now=True, default=datetime.datetime.now())

    def __unicode__(self):
        if self.addon_name:
            return u"%s (%s)" % (self.display_name, self.addon_name)
        else:
            return u"%s" % self.display_name

    class Meta:
        verbose_name = _(u"sonde")
        ordering = ['display_name', 'addon_name']


class Server(models.Model):
    hostname = models.CharField(max_length=255, verbose_name=_(u"Nom du serveur"))
    ip = models.CharField(max_length=255, verbose_name=_(u"Adresse IP"), blank=True)
    state = models.BooleanField(verbose_name=_(u"Serveur accessible ?"), default=False)
    is_measuring = models.BooleanField(verbose_name=_(u"Serveur en cours de mesures ?"), default=False)
    username = models.CharField(max_length=50, verbose_name=_(u"Nom d'utilisateur SSH"), blank=True, default="")
    password = EncryptedCharField(max_length=50, verbose_name=_(u"Mot de passe SSH"), blank=True, default="")
    date_created = models.DateTimeField(verbose_name=_(u"Date de création"), null=True, auto_now_add=True, default=datetime.datetime.now())
    date_modified = models.DateTimeField(verbose_name=_(u"Date de modification"), null=True, auto_now=True, default=datetime.datetime.now())
    probes = models.ManyToManyField(Probe, verbose_name=_(u"Sondes"), blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.hostname

    @models.permalink
    def get_absolute_url(self):
        return ('server-detail', [self.id])

    class Meta:
        verbose_name = _(u"serveur")
        ordering = ['hostname', 'ip']


class ServerGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name=_(u"Nom du groupe"))
    date_created = models.DateTimeField(verbose_name=_(u"Date de création"), null=True, auto_now_add=True, default=datetime.datetime.now())
    date_modified = models.DateTimeField(verbose_name=_(u"Date de modification"), null=True, auto_now=True, default=datetime.datetime.now())
    servers = models.ManyToManyField(Server, verbose_name=_(u"Serveurs"), blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.name

    class Meta:
        verbose_name = _(u"groupe de serveurs")
        verbose_name_plural = _(u"groupes de serveurs")
        ordering = ['name']


class Measure(models.Model):
    timestamp = models.DateTimeField(verbose_name=_(u"Date et heure"))
    server = models.ForeignKey(Server, verbose_name=_(u"Serveur"))
    probe = models.ForeignKey(Probe, verbose_name=_(u"Sonde"))
    value = models.CharField(max_length=4096, verbose_name=_(u"Valeur mesurée"))

    def __unicode__(self):
        return u"%s %s %s" % (self.timestamp, self.server.hostname, self.probe.display_name)

    class Meta:
        verbose_name = _(u"mesure")
        verbose_name_plural = _(u"mesures")
        ordering = ['-timestamp', 'server', 'probe']


class MeasureDay(models.Model):
    timestamp = models.DateTimeField(verbose_name=_(u"Date et heure"))
    server = models.ForeignKey(Server, verbose_name=_(u"Serveur"))
    probe = models.ForeignKey(Probe, verbose_name=_(u"Sonde"))
    value = models.CharField(max_length=4096, verbose_name=_(u"Valeur mesurée"))

    def __unicode__(self):
        return u"%s" % self.value

    class Meta:
        verbose_name = _(u"mesure (vue journalière)")
        verbose_name_plural = _(u"mesures (vue journalière)")
        ordering = ['-timestamp', 'server', 'probe']


class MeasureWeek(models.Model):
    timestamp = models.DateTimeField(verbose_name=_(u"Date et heure"))
    server = models.ForeignKey(Server, verbose_name=_(u"Serveur"))
    probe = models.ForeignKey(Probe, verbose_name=_(u"Sonde"))
    value = models.CharField(max_length=4096, verbose_name=_(u"Valeur mesurée"))

    def __unicode__(self):
        return u"%s" % self.value

    class Meta:
        verbose_name = _(u"mesure (vue hebdomadaire)")
        verbose_name_plural = _(u"mesures (vue hebdomadaire)")
        ordering = ['-timestamp', 'server', 'probe']


class MeasureMonth(models.Model):
    timestamp = models.DateTimeField(verbose_name=_(u"Date et heure"))
    server = models.ForeignKey(Server, verbose_name=_(u"Serveur"))
    probe = models.ForeignKey(Probe, verbose_name=_(u"Sonde"))
    value = models.CharField(max_length=4096, verbose_name=_(u"Valeur mesurée"))

    def __unicode__(self):
        return u"%s" % self.value

    class Meta:
        verbose_name = _(u"mesure (vue mensuelle)")
        verbose_name_plural = _(u"mesures (vue mensuelle)")
        ordering = ['-timestamp', 'server', 'probe']


class CronLog(models.Model):
    timestamp = models.DateTimeField(verbose_name=_(u"Date et heure"))
    action = models.CharField(max_length=50, verbose_name=_(u"Serveur"), blank=True)
    server = models.ForeignKey(Server, verbose_name=_(u"Serveur"), null=True)
    success = models.BooleanField(verbose_name=_(u"Succès de l'exécution ?"), default=False)
    message = models.TextField(verbose_name=_(u"Message"), null=True, default="")
    duration = models.FloatField(verbose_name=_(u"Durée en secondes"), default=0)

    def __unicode__(self):
        return u"%s %s %s %s" % (self.timestamp, self.server.hostname, self.success, self.duration)

    class Meta:
        verbose_name = _(u"exécution de tâches cron")
        verbose_name_plural = _(u"exécutions de tâches cron")
        ordering = ['-timestamp', '-server', '-action', ]

skwissh/templates/cronlog_list.html
{% extends "base/base.html" %}
{% load i18n %}

{% block content %}
{% include "base/navigation.html" %}

<section>
	<ul class="nav-bar">
		<li><a class="bigger">{% trans "Rapport des sondes" %}</a></li>
	</ul>
	<div class="panel">
	    {% if is_paginated %}
		        <ul class="pagination">
		        	{% if page_obj.has_previous %}
		        	<li class="arrow"><a href="{% url logs-list %}?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		        	{% else %}
		        	<li class="arrow inactive">&laquo;</li>
		        	{% endif %}
		        	{% for i in page_obj.paginator.page_range %}
	  				<li {% ifequal i page_obj.number %}class="current"{% endifequal %}><a href="{% url logs-list %}?page={{ i }}">{{ i }}</a></li>
	  				{% endfor %}
	  				{% if page_obj.has_next %}
	  				<li class="arrow"><a href="{% url logs-list %}?page={{ page_obj.next_page_number }}">&raquo;</a></li>
		        	{% else %}
		        	<li class="arrow inactive">&raquo;</li>
		        	{% endif %}
				</ul>
    	{% endif %}		
	    <table id="cronlogs-table">
	    	<thead>
	    		<th>{% trans "Date / heure" %}</th>
	    		<th>{% trans "Serveur" %}</th>
	    		<th>{% trans "Action" %}</th>
	    		<th>{% trans "Durée totale" %}</th>
	    		<th colspan="3">{% trans "Status" %}</th>
	    	</thead>
	    	<tbody>
	        {% for log in object_list %}
	            <tr>
	                <td>{% ifchanged %}{{ log.timestamp }}{% endifchanged %}</td>
	                {% if log.server %}
	                <td><a href="{% url server-detail log.server.id %}">{{ log.server.hostname }}</a></td>
	                {% else %}
	                <td></td>
	                {% endif %}
	                <td>{{ log.action }}</td>
	                <td>{{ log.duration|floatformat:2 }} {% trans 'secondes' %}</td>
	                {% if log.success %}
	                <td>{% trans 'OK'%}</td>
	                <td class="log up">&nbsp;</td>
	                {% else %}
	                <td>{% trans 'Erreur'%}</td>
	                <td class="log down">&nbsp;</td>
	                {% endif %}
	                <td><a data-id="{{ log.id }}" class="show-details" href="#">{% trans 'Voir les détails...' %}</a></td>
	            </tr>
	            <tr class="log-details" id="details-{{ log.id }}">
	            	<td></td>
	            	<td colspan="6"><textarea disabled>{{ log.message }}</textarea></td>
	            </tr>
	        {% endfor %}
	        </tbody>
	    </table>	        
	    {% if is_paginated %}
		        <ul class="pagination">
		        	{% if page_obj.has_previous %}
		        	<li class="arrow"><a href="{% url logs-list %}?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		        	{% else %}
		        	<li class="arrow inactive">&laquo;</li>
		        	{% endif %}
		        	{% for i in page_obj.paginator.page_range %}
	  				<li {% ifequal i page_obj.number %}class="current"{% endifequal %}><a href="{% url logs-list %}?page={{ i }}">{{ i }}</a></li>
	  				{% endfor %}
	  				{% if page_obj.has_next %}
	  				<li class="arrow"><a href="{% url logs-list %}?page={{ page_obj.next_page_number }}">&raquo;</a></li>
		        	{% else %}
		        	<li class="arrow inactive">&raquo;</li>
		        	{% endif %}
				</ul>
    	{% endif %}
    </div>
</section>
{% endblock content %}

{% block javascript %}
<script type="text/javascript">
$('#cronlogs-table').delegate('.show-details', 'click', function(e){
	e.preventDefault();
	$("#details-" + $(this).data("id")).toggle();
});
</script>
{% endblock javascript %}

skwissh/templates/modal-add-probe.html
{% load i18n %}
<div id="add-probe" class="reveal-modal medium add">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% trans 'Ajouter une sonde' %}</a>
		</li>
	</ul>
	<div class="panel">
		<form action="{% url add-probe %}" method="post">
			{% csrf_token %}
			{{ probe_form.as_table }}
			<input class="right small success button radius" type="submit" value="{% trans 'Sauvegarder' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Annuler' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-add-server.html
{% load i18n %}
<div id="add-server" class="reveal-modal medium add">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% trans "Ajout d'un serveur" %}</a>
		</li>
	</ul>
	<div class="panel">
		<form action="{% url add-server %}" method="post">
			{% csrf_token %}
			{{ server_form.as_table }}
			<input class="right small success button radius" type="submit" value="{% trans 'Sauvegarder' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Annuler' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-delete-probe.html
{% load i18n %}
<div id="delete-probe-{{ probe.id }}" class="reveal-modal medium delete">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% blocktrans with name=probe.display_name %}Supprimer la sonde '{{ name }}' ?{% endblocktrans %}</a>
		</li>
	</ul>
	<div class="panel">
		<form action="{% url delete-probe probe.id %}" method="post">
			<p>
				{% trans 'La suppression de cette sonde entraînera la suppression de toutes les mesures associées.' %}
			</p>
			<p>
				{% blocktrans with count=probe.measure_set.count %}{{ count }} mesures seront définitivement perdues.{% endblocktrans %}
				{% trans 'Cette opération est irréversible.' %}
			</p>
			<p>
				{% blocktrans with name=probe.display_name %}Voulez vous vraiment supprimer la sonde '{{ name }}' ?{% endblocktrans %}
			</p>
			{% csrf_token %}
			<input class="right small success button radius" type="submit" value="{% trans 'Oui' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Non' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-delete-server-group.html
{% load i18n %}
<div id="delete-group-{{ group.id }}" class="reveal-modal medium delete">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% blocktrans with name=group.name %}Supprimer le groupe de serveurs '{{ name }}' ?{% endblocktrans %}</a>
		</li>
	</ul>
	<div class="panel">
		<p>
			{% trans 'Les serveurs inclus dans ce groupe ne seront pas supprimés.' %}
			{% trans "Vous pourrez les retrouver dans la zone 'Non Classés'." %}
		</p>
		<p>
			{% blocktrans with name=group.name %}Etes-vous sûr de vouloir supprimer le groupe de serveurs '{{ name }}' ?{% endblocktrans %}
		</p>
		<form action="{% url delete-group group.id %}" method="post">
			{% csrf_token %}
			<input class="right small success button radius" type="submit" value="{% trans 'Oui' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Non' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-delete-server.html
{% load i18n %}
<div id="delete-server-{{ server.id }}" class="reveal-modal medium delete">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% blocktrans with name=server.hostname %}Supprimer le serveur '{{ name }}' ?{% endblocktrans %}</a>
		</li>
	</ul>
	<div class="panel">
		<p>
			{% trans 'La suppression de ce serveur entraînera la suppression de toutes les mesures associées.' %}
		</p>
		<p>
			{% blocktrans with count=server.measure_set.count %}{{ count }} mesures seront définitivement perdues.{% endblocktrans %}
			{% trans 'Cette opération est irréversible.' %}
		</p>
		<p>
			{% blocktrans with name=server.hostname %}Voulez vous vraiment supprimer le serveur '{{ name }}' ?{% endblocktrans %}
		</p>
		<form action="{% url delete-server server.id %}" method="post">
			{% csrf_token %}
			<input class="right small success button radius" type="submit" value="{% trans 'Oui' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Non' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-edit-server.html
{% load i18n %}
<div id="edit-server" class="reveal-modal medium add">
	<ul class="nav-bar">
		<li>
			<a class="bigger nolink" href="#">{% blocktrans with name=server.hostname %}Editer le serveur '{{ name }}'{% endblocktrans %}</a>
		</li>
	</ul>
	<div class="panel">
		<form action="{% url update-server server.pk %}" method="post">
			{% csrf_token %}
			{{ server_form.as_table }}
			<input class="right small success button radius" type="submit" value="{% trans 'Sauvegarder' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Annuler' %}</a>
		</form>
	</div>
</div>

skwissh/templates/modal-update-probe.html
{% load i18n %}
<form method="post" action="{% url update-probe  %}">
	{{ probe_formset.management_form }}
	{% for form in probe_formset %}
	<div id='edit-probe-{{ form.id.value }}' class="reveal-modal medium update">
		<ul class="nav-bar">
			<li>
				{% with name=form.display_name.value %}
				<a class="bigger nolink" href="#">{% blocktrans %}Editer la sonde '{{ name }}'{% endblocktrans %}</a>
				{% endwith %}
			</li>
		</ul>
		<div class="panel">
			{% csrf_token %}
			{{ form.as_table }}
			<input class="right small success button radius" type="submit" value="{% trans 'Sauvegarder' %}" />
			<a href="#" class="right small alert button radius" onclick="javascript:$('.reveal-modal-bg').click();">{% trans 'Annuler' %}</a>
		</div>
	</div>
	{% endfor %}
</form>

skwissh/templates/section-probe.html
{% load i18n %}
<section class="probe" id="probe-{{ probe.id }}">
	<ul class="nav-bar">
		{% if user.is_staff %}
		<li class="has-flyout">
			<a class="bigger" href="#probe-{{ probe.id }}">{{ probe.display_name }}{% ifnotequal probe.addon_name "" %}{% ifnotequal probe.addon_name None %} ({{ probe.addon_name }}){% endifnotequal %}{% endifnotequal %}</a>
			<a href="#" class="flyout-toggle"><span></span></a>
			<ul class="flyout">
				<li class="edit"><a title="{% trans 'Editer cette sonde' %}..." href="#" data-reveal-id="edit-probe-{{ probe.id }}">{% trans 'Editer' %}...</a></li>
				<li class="delete"><a title="{% trans 'Supprimer cette sonde' %}..." href="#" data-reveal-id="delete-probe-{{ probe.id }}">{% trans 'Supprimer' %}...</a></li>
			</ul>
		</li>
		{% else %}
		<li><a class="bigger" href="#probe-{{ probe.id }}">{{ probe.display_name }}{% ifnotequal probe.addon_name "" %}{% ifnotequal probe.addon_name None %} ({{ probe.addon_name }}){% endifnotequal %}{% endifnotequal %}</a></li>
		{% endif %}
	</ul>
	<div class="panel">
		<div class="row">
			<div class="two columns">
				<div class="probe-type {{ probe.graph_type.name }}"></div>
				<div class="graph-type-text">
					{% ifequal probe.graph_type.name "linegraph" %}{% trans 'Graphique en lignes' %}{% endifequal %}
					{% ifequal probe.graph_type.name "linegraph_stacked" %}{% trans 'Graphique en lignes empilées' %}{% endifequal %}
					{% ifequal probe.graph_type.name "bargraph" %}{% trans 'Histogramme empilé' %}{% endifequal %}
					{% ifequal probe.graph_type.name "bargraph_groups" %}{% trans 'Histogramme par groupe' %}{% endifequal %}
					{% ifequal probe.graph_type.name "pie" %}{% trans 'Graphique camembert' %}{% endifequal %}
					{% ifequal probe.graph_type.name "text" %}{% trans 'Sortie texte' %}{% endifequal %}
				</div>
				<div class="probe-mesures-count">
					{{ probe.measure_set.count }} {% trans 'mesures effectuées'%}
				</div>
				<div class="probe-servers-count">
					{% trans 'Actuellement sur'%} {{ probe.server_set.count }} {% trans 'serveurs'%}
				</div>
			</div>
			<div class="ten columns">
				<form class="custom">
					<div class="row">
						<div class="two columns">
							<label class="inline" for="ssh-{{ probe.id }}">{% trans 'Commande SSH' %}</label>
						</div>
						<div class="ten columns">
							<input id="ssh-{{ probe.id }}" type="text" disabled value="$ {{ probe.ssh_command }}"/>
						</div>
					</div>
					<div class="row">
						<div class="two columns">
							<label class="inline" for="sudo-{{ probe.id }}">{% trans "Utilise 'sudo' ?" %}</label>
						</div>
						<div class="ten columns">
							<input class="custom checkbox yes" id="sudo-{{ probe.id }}" type="checkbox" disabled {% if probe.use_sudo %}checked{% endif %}/>
							{% trans 'Oui' %}
							<input class="custom checkbox no" id="sudo-{{ probe.id }}" type="checkbox" disabled {% if not probe.use_sudo %}checked{% endif %}/>
							{% trans 'Non' %}
						</div>
					</div>
					<div class="row">
						<div class="two columns">
							<label class="inline" for="python-{{ probe.id }}">{% trans 'Commande Python' %}</label>
						</div>
						<div class="ten columns">
							<textarea id="python-{{ probe.id }}" disabled>&gt;&gt;&gt; {{ probe.python_parse }}</textarea>
						</div>
					</div>
					{% ifnotequal probe.graph_type.name "text" %}
					<div class="row">
						<div class="two columns">
							<label class="inline" for="unit-{{ probe.id }}">{% trans 'Unités' %}</label>
						</div>
						<div class="ten columns">
							<input id="unit-{{ probe.id }}" type="text" disabled value="{{ probe.probe_unit }}"/>
						</div>
					</div>
					<div class="row">
						<div class="two columns">
							<label class="inline" for="labels-{{ probe.id }}">{% trans 'Libéllés' %}</label>
						</div>
						<div class="ten columns">
							<input id="unit-{{ probe.id }}" type="text" disabled value="{{ probe.probe_labels }}"/>
						</div>
					</div>					
					{% endifnotequal %}
				</form>
			</div>
		</div>
	</div>
</section>

skwissh/templates/server-detail.html
{% extends "base/base.html" %}
{% load i18n %}

{% block content %}
	{% include "base/navigation.html" with nb_mesures=server.measure_set.count %}
	{% for probe in server.probes.all %}
		{% include "section-graph.html" %}
	{% endfor %}
{% endblock content %}

{% block container %}
	{% if user.is_staff %}
		{% if form.errors %}
			{% with server_form=form %}
			{% include "modal-edit-server.html" %}
			{% endwith %}
		{% else %}
			{% include "modal-edit-server.html" %}
		{% endif %}
	{% endif %}
{% endblock container %}

{% block javascript %}
	{% if form.errors %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('#edit-server').reveal();
		}); 
	</script>
	{% endif %}	
	{% include "skwissh_graphs.js" %}
{% endblock javascript %}